"""Project generator - Creates project files from agent outputs."""
import os
from pathlib import Path
from typing import Dict, Any
from datetime import datetime
from config import settings


class ProjectGenerator:
    """Generates complete project structure from agent outputs."""
    
    def __init__(self, project_id: int, prompt: str, agent_outputs: Dict[str, Any]):
        self.project_id = project_id
        self.prompt = prompt
        self.agent_outputs = agent_outputs
        self.project_name = self._generate_project_name()
        
    def _generate_project_name(self) -> str:
        """Generate a project name from the prompt."""
        # Extract first few words and sanitize
        words = self.prompt.split()[:4]
        name = "_".join(words).lower()
        # Remove special characters
        name = "".join(c if c.isalnum() or c == "_" else "" for c in name)
        # Add timestamp
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        return f"{name}_{timestamp}"
    
    async def generate(self) -> str:
        """Generate the complete project structure."""
        # Create project directory
        project_path = Path(settings.projects_dir) / self.project_name
        project_path.mkdir(parents=True, exist_ok=True)
        
        print(f"   📁 Creating project at: {project_path}")
        
        # Collect all artifacts from all agents
        all_artifacts = {}
        for agent_name, agent_data in self.agent_outputs.items():
            artifacts = agent_data.get("artifacts", {})
            all_artifacts.update(artifacts)
        
        # Write all files
        for file_path, content in all_artifacts.items():
            full_path = project_path / file_path
            full_path.parent.mkdir(parents=True, exist_ok=True)
            
            with open(full_path, "w", encoding="utf-8") as f:
                f.write(content)
        
        # Generate additional meta files
        self._generate_readme(project_path)
        self._generate_docker_files(project_path)
        self._generate_gitignore(project_path)
        
        print(f"   ✓ Generated {len(all_artifacts)} files")
        
        return str(project_path)
    
    def _generate_readme(self, project_path: Path):
        """Generate project README."""
        readme_content = f"""# {self.project_name.replace('_', ' ').title()}

## Overview

{self.prompt}

This project was automatically generated by the Autonomous AI Software Company.

## Project Structure

```
{self.project_name}/
├── backend/           # Python FastAPI backend
├── frontend/          # Next.js frontend
├── tests/             # Test suites
└── docs/              # Documentation
```

## Getting Started

### Backend

1. Navigate to backend directory:
```bash
cd backend
```

2. Create virtual environment:
```bash
python -m venv venv
source venv/bin/activate  # Windows: venv\\Scripts\\activate
```

3. Install dependencies:
```bash
pip install -r requirements.txt
```

4. Set up environment:
```bash
cp .env.example .env
# Edit .env with your configuration
```

5. Run the server:
```bash
uvicorn main:app --reload
```

### Frontend

1. Navigate to frontend directory:
```bash
cd frontend
```

2. Install dependencies:
```bash
npm install
```

3. Set up environment:
```bash
cp .env.local.example .env.local
# Edit .env.local with your configuration
```

4. Run development server:
```bash
npm run dev
```

### Running Tests

Backend tests:
```bash
cd backend
pytest
```

Frontend tests:
```bash
cd frontend
npm test
```

## Generated Documentation

- `docs/product_requirements.md` - Product Requirements Document
- `docs/architecture.md` - System Architecture
- `docs/code_review_report.md` - Code Review Report

## API Documentation

Once the backend is running, visit:
- Swagger UI: http://localhost:8000/docs
- ReDoc: http://localhost:8000/redoc

## Frontend

Once the frontend is running, visit:
- http://localhost:3000

## Docker Support

Build and run with Docker:

```bash
docker-compose up --build
```

## Generated By

Autonomous AI Software Company
- Product Manager Agent
- Software Architect Agent
- Backend Developer Agent
- Frontend Developer Agent
- QA Tester Agent
- Code Reviewer Agent

## License

MIT License

---

*This project was automatically generated on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}*
"""
        
        readme_path = project_path / "README.md"
        with open(readme_path, "w", encoding="utf-8") as f:
            f.write(readme_content)
    
    def _generate_docker_files(self, project_path: Path):
        """Generate Docker configuration."""
        
        # Dockerfile for backend
        backend_dockerfile = """FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
"""
        
        # Dockerfile for frontend
        frontend_dockerfile = """FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

RUN npm run build

CMD ["npm", "start"]
"""
        
        # Docker Compose
        docker_compose = """version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./app.db
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
"""
        
        # Write Docker files
        backend_docker_path = project_path / "backend" / "Dockerfile"
        if backend_docker_path.parent.exists():
            with open(backend_docker_path, "w") as f:
                f.write(backend_dockerfile)
        
        frontend_docker_path = project_path / "frontend" / "Dockerfile"
        if frontend_docker_path.parent.exists():
            with open(frontend_docker_path, "w") as f:
                f.write(frontend_dockerfile)
        
        compose_path = project_path / "docker-compose.yml"
        with open(compose_path, "w") as f:
            f.write(docker_compose)
    
    def _generate_gitignore(self, project_path: Path):
        """Generate .gitignore file."""
        gitignore_content = """# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
env/
venv/
ENV/
*.egg-info/
.pytest_cache/
.coverage
htmlcov/

# Node.js
node_modules/
npm-debug.log*
yarn-debug.log*
yarn-error.log*
.next/
out/
.cache/

# Environment
.env
.env.local
.env.*.local

# IDE
.vscode/
.idea/
*.swp
*.swo
*~

# OS
.DS_Store
Thumbs.db

# Databases
*.db
*.sqlite
*.sqlite3

# Logs
*.log
logs/

# Build
build/
dist/
"""
        
        gitignore_path = project_path / ".gitignore"
        with open(gitignore_path, "w") as f:
            f.write(gitignore_content)
